# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ship It Party
description: > # this means to ignore newlines until "baseurl:"
  Sometimes you just need to push through and make the decesion you have been thinking about. How do you do this you ask? You just Ship It! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shipit.party" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
